### ISSUE TITLE
how you get training.txt and testing.txt ;can you expain?

### ISSUE THREAD

**Issue by ranjiewwen** [Pratik-Chhajer/Predicting-Photography-Aesthetics-with-CNNs#1]
- i know adda dataset , it has attritute and scores, so it don't has total scores . while you training.txt you get one score for every image? can you show me how you get this or the code ?

**Comment by Pratik-Chhajer** [comment]
I actually created a script to read the scores which were in following form **score_fileName.jpg**, for example *0.05_farm001.jpg*.  
You can access these images from [here](https://drive.google.com/drive/folders/0BxeylfSgpk1MOVduWGxyVlJFUHM), click that link and go to AADB_newtest.zip

![aadb](https://user-images.githubusercontent.com/25812641/41146054-b3c6e29c-6b1f-11e8-910e-406335c1d4fe.PNG)

**Comment by ranjiewwen** [comment]
ok , thanks , the dataset has a total scores.

so in your experiment ,you don't use the attribute label score ,only use the image total scores?

**Comment by Pratik-Chhajer** [comment]
Yes, only image total score was used.

Please note that it was a purely machine learning solution, no image processing used.

**Comment by Pratik-Chhajer** [comment]
Closing this issue as confusion with source of scores is resolved now
